---
- name: update all yum packages
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: install dependencies
  yum:
    name: "{{ item }}"
  with_items:
    - gcc
    - gcc-c++
    - ncurses-devel
    - openssl-devel
    - pkgconfig
    - protobuf-compiler
    - protobuf-devel
